# Generated by Django 4.1.5 on 2023-01-31 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pic')),
                ('original_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='comment_box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msg', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product_collection')),
            ],
        ),
    ]
